#!/bin/bash

DADAPUSH_CHANNEL_TOKEN=$1

if [ -z "$DADAPUSH_CHANNEL_TOKEN" ]
then
   echo "No channel token specified"
fi


# Service          
export NAGIOS_HOSTALIAS='server.example.com'
export NAGIOS_HOSTNAME='server.example.com'
export NAGIOS_NOTIFICATIONTYPE='PROBLEM'
export NAGIOS_SERVICEDESC='Memory Usage'
export NAGIOS_HOSTGROUPNAME='Linux Servers';
export NAGIOS_SHORTDATETIME='05-10-2012 21:30:17'
export NAGIOS_SERVICESTATE='WARNING'
export NAGIOS_HOSTADDRESS='192.168.1.2'
export NAGIOS_SERVICEOUTPUT='WARNING'
../nagios-dadapush.sh -a "$NAGIOS_NOTIFICATIONTYPE" -b "$NAGIOS_HOSTNAME" -e "$NAGIOS_SERVICEDESC" -f "$NAGIOS_SERVICESTATE" -g "$NAGIOS_SERVICEOUTPUT" -T "$DADAPUSH_CHANNEL_TOKEN"

export NAGIOS_NOTIFICATIONTYPE='ACKNOWLEDGEMENT'
../nagios-dadapush.sh -a "$NAGIOS_NOTIFICATIONTYPE" -b "$NAGIOS_HOSTNAME" -e "$NAGIOS_SERVICEDESC" -f "$NAGIOS_SERVICESTATE" -g "$NAGIOS_SERVICEOUTPUT" -T "$DADAPUSH_CHANNEL_TOKEN"
