#!/bin/bash

DADAPUSH_CHANNEL_TOKEN=$1

if [ -z "$DADAPUSH_CHANNEL_TOKEN" ]
then
   echo "No channel token specified"
fi

# Host 
export NAGIOS_HOSTNAME='server.example.com'
export NAGIOS_HOSTALIAS='server.example.com'
export NAGIOS_HOSTADDRESS='192.168.1.2'
export NAGIOS_HOSTGROUPNAMES='Linux Servers'
export NAGIOS_SHORTDATETIME='05-10-2012 22:22:23'


export NAGIOS_NOTIFICATIONTYPE='PROBLEM'
export NAGIOS_HOSTSTATE='DOWN'
export NAGIOS_HOSTOUTPUT='CRITICAL - Host Unreachable (192.168.1.2)'
../nagios-dadapush.sh -a "$NAGIOS_NOTIFICATIONTYPE" -b "$NAGIOS_HOSTNAME" -c "$NAGIOS_HOSTSTATE" -d "$NAGIOS_HOSTOUTPUT" -T "$DADAPUSH_CHANNEL_TOKEN"

export NAGIOS_NOTIFICATIONTYPE='RECOVERY'
export NAGIOS_HOSTSTATE='UP'
export NAGIOS_HOSTOUTPUT='It is up'
../nagios-dadapush.sh -a "$NAGIOS_NOTIFICATIONTYPE" -b "$NAGIOS_HOSTNAME" -c "$NAGIOS_HOSTSTATE" -d "$NAGIOS_HOSTOUTPUT" -T "$DADAPUSH_CHANNEL_TOKEN"

export NAGIOS_NOTIFICATIONTYPE='ACKNOWLEDGEMENT'
export NAGIOS_HOSTSTATE='UP'
export NAGIOS_HOSTOUTPUT='It is up'
../nagios-dadapush.sh -a "$NAGIOS_NOTIFICATIONTYPE" -b "$NAGIOS_HOSTNAME" -c "$NAGIOS_HOSTSTATE" -d "$NAGIOS_HOSTOUTPUT" -T "$DADAPUSH_CHANNEL_TOKEN"
